replicaCount: 1

image:
  repository: xupaky/spring-petclinic
  tag: "v2.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
